# Setup
title:               Dragon Debt          
description:         "We're here to #burnthebudget at UIC"
url:                 https://dragondebt.com
baseurl:             ''
paginate:            3
paginate_path:       '/news/page:num'
permalink:           pretty
shareimage:          https://repository-images.githubusercontent.com/323440042/eeb93b80-7ba1-11eb-9543-960f7661de88

# About/contact
author:
  name:              Dragon Debt
  url:               https://twitter.com/dragondebt
  email:             DragonDebtUIC@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.1
google_analytics_id: 

# Image Gallery  
imagesurl: "/public/images/shares"
thumbsurl: "/public/images/thumbs/"


# Social Media Links In Sidebar
social-media:
  facebook:
    id:
    href: 'https://www.facebook.com/'
    title: 'Facebook'
    fa-icon: 'fab fa-facebook-square'

  twitter:
    id: 'dragondebt'
    href: 'https://www.twitter.com/'
    title: 'Twitter'
    fa-icon: 'fab fa-twitter-square'

  github:
    id:
    href: 'https://github.com/'
    title: 'GitHub'
    fa-icon: 'fab fa-github-square'

  instagram:
    id: 'dragondebtuic'
    href: 'https://instagram.com/'
    title: 'Instagram'
    fa-icon: 'fab fa-instagram'

  youtube:
    id:
    href: 'https://youtube.com/'
    title: 'YouTube'
    fa-icon: 'fab fa-youtube'

  tiktok:
    id: '@dragondebt'
    href: 'https://tiktok.com/'
    title: 'TikTok'
    fa-icon: 'fab fa-tiktok'
  