# Setup
title:               Slay The Dragon
tagline:             'Burn The Budget'
description:         'A test blog'
url:                 http://dragondebtuic.github.io/
baseurl:             http://dragondebtuic.github.io/
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Dragon Debt
  url:               https://twitter.com/dragondebt
  email:             dragondebt@example.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
