# Setup
title:               Dragon Debt
tagline:             'A Debt Story'
description:         'Welcome to our new site, please pardon our appearance while we set everything up'
url:                 https://dragondebtuic.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Dragon Debt
  url:               https://twitter.com/dragondebt
  email:             Dragondebt@example.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.1
#google_analytics_id: UA-146052-15
