# Setup
title:               Dragon Debt
tagline:             '#BurnTheBudget'
description:         'Welcome to our new site, please pardon our appearance while we set everything up'
url:                 https://dragondebtuic.github.io/
baseurl:             ''
paginate:            5
paginate_path:       '/news/page:num'
permalink:           pretty

# About/contact
author:
  name:              Dragon Debt
  url:               https://twitter.com/dragondebt
  email:             DragonDebtUIC@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.1
#google_analytics_id: UA-146052-15

social-media:
  facebook:
    id:
    href: 'https://www.facebook.com/'
    title: 'Facebook'
    fa-icon: 'fa-facebook-square'

  twitter:
    id: 'dragondebt'
    href: 'https://www.twitter.com/'
    title: 'Twitter'
    fa-icon: 'fa-twitter-square'

  github:
    id:
    href: 'https://github.com/'
    title: 'GitHub'
    fa-icon: 'fa-github-square'

  instagram:
    id: 'dragondebtuic'
    href: 'https://instagram.com/'
    title: 'Instagram'
    fa-icon: 'fa-instagram'

  youtube:
    id:
    href: 'https://youtube.com/'
    title: 'YouTube'
    fa-icon: 'fa-youtube'

  tiktok:
    id: '@dragondebt'
    href: 'https://tiktok.com/'
    title: 'TikTok'
    fa-icon: 'fa-tiktok'